name: Upload CSV to BigQuery

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at 3:00 AM Uganda time (midnight UTC)
  workflow_dispatch:

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}'

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: jiburawdata

      - name: Download CSV from Metabase link
        run: |
          curl -L "https://sema.jibuco.com/public/question/cabced83-1d94-4e16-8e8f-e2b2a38eecaa.csv

      - name: Delete old BigQuery table (if it exists)
        run: |
          bq rm -f jiburawdata:jibu_data.raw_sales_2025

      - name: Upload CSV to BigQuery
        run: |
          bq load --source_format=CSV --autodetect jiburawdata:jibu_data.raw_sales_2025 data.csv
